import { PageConfig } from './page-config.model';

export class TabConfig {
  /**
   * Configuration of the page to be shown in the tab.
   */
  page: PageConfig = new PageConfig();

  /**
   * Current ID of the tab with the page.
   * Generated by Chrome.
   */
  tabId: number = 0;

  /**
   * Indicates if the page is successfully loaded.
   */
  tabIdReady: boolean = false;

  /**
   * ID of the tab refreshed version of the page that will be shown next.
   * Generated by Chrome.
   */
  nextTabId: number = 0;

  /**
   * Indicates if the refreshed version of the page is successfully loaded.
   */
  nextTabIdReady: boolean = false;

  /**
   * Indicates if the tab is active (current).
   */
  active: boolean = false;

  /**
   * Number of the current retry to load the page.
   */
  retryCount: number = 0;

  /**
   * Timer to reload the page.
   */
  reloadTimer?: number | ReturnType<typeof setInterval>;

  /**
   * Internal one-shot flag: when true, the next preload warming cycle should skip
   * creating a new preload tab for this page. Used after promoting an existing
   * preload to primary so we don't immediately recreate another preload in the
   * same rotation tick (which complicates promotion tests and can add churn).
   */
  skipNextPreload?: boolean;

  /** Timestamp (ms since epoch) when a preload->primary promotion occurred. Used to suppress immediate redundant preloads. */
  lastPromotionAt?: number;

  /** If true the page is in error state and temporarily skipped in rotation until a successful load clears it. */
  suspended?: boolean;

  /** Timestamp of last handled navigation error (ms since epoch) for throttling duplicate error events. */
  lastErrorAt?: number;

  constructor(init?: Partial<TabConfig>) {
    Object.assign(this, init);
  }
}
