import { PageConfig } from './page-config.model';

export class TabConfig {
  /**
   * Configuration of the page to be shown in the tab.
   */
  page: PageConfig = new PageConfig();

  /**
   * Current ID of the tab with the page.
   * Generated by Chrome.
   */
  tabId: number = 0;

  /**
   * Indicates if the page is successfully loaded.
   */
  tabIdReady: boolean = false;

  /**
   * ID of the tab refreshed version of the page that will be shown next.
   * Generated by Chrome.
   */
  nextTabId: number = 0;

  /**
   * Indicates if the refreshed version of the page is successfully loaded.
   */
  nextTabIdReady: boolean = false;

  /**
   * Indicates if the tab is active (current).
   */
  active: boolean = false;

  /**
   * Number of the current retry to load the page.
   */
  retryCount: number = 0;

  /**
   * Timer to reload the page.
   */
  reloadTimer?: number | ReturnType<typeof setInterval>;

  /**
   * Internal one-shot flag: when true, the next preload warming cycle should skip
   * creating a new preload tab for this page. Used after promoting an existing
   * preload to primary so we don't immediately recreate another preload in the
   * same rotation tick (which complicates promotion tests and can add churn).
   */
  skipNextPreload?: boolean;

  /** Timestamp (ms since epoch) when a preload->primary promotion occurred. Used to suppress immediate redundant preloads. */
  lastPromotionAt?: number;

  /** If true the page is in error state and temporarily skipped in rotation until a successful load clears it. */
  suspended?: boolean;

  /** Timestamp of last handled navigation error (ms since epoch) for throttling duplicate error events. */
  lastErrorAt?: number;

  /** Consecutive failed preload promotions or readiness timeouts. */
  preloadFailureCount?: number;
  /** Earliest timestamp (ms) when a new preload attempt is allowed (backoff window). */
  nextPreloadAllowedAt?: number;
  /** Current backoff delay applied (ms) for preload attempts, exponential growth with cap. */
  currentPreloadBackoffMs?: number;

  /** Timestamp when current preload (nextTabId) was created. */
  preloadCreationAt?: number;
  /** Count of chrome.tabs.onUpdated events observed for current preload during initial wait. */
  preloadOnUpdatedCount?: number;
  /** Milliseconds spent waiting in last waitForInitialLoad for the preload. */
  lastPreloadWaitMs?: number;
  /** Outcome classification of last waitForInitialLoad: 'complete' | 'timeout' | 'error'. */
  lastPreloadWaitOutcome?: 'complete' | 'timeout' | 'error';
  /** Whether status=complete was ever observed for the preload prior to promotion/discard. */
  preloadCompleteObserved?: boolean;

  /** Ordered list of status (and limited changeInfo flags) observed for the current preload via onUpdated before completion or timeout. */
  preloadStatusesSeen?: string[];

  /** Distinct from preload timing: time spent waiting for initial primary (tabId) creation load. */
  primaryInitialWaitMs?: number;
  /** Outcome for initial primary load: mirrors preload outcomes but tracked separately. */
  primaryInitialWaitOutcome?: 'complete' | 'timeout' | 'error';

  /** Historical ring buffer of previous preload attempts (most recent first). Each entry: {at, waitMs, outcome, onUpdatedCount, statuses, reason, httpStatus?, url}. */
  preloadHistory?: Array<{
    at: number;
    waitMs?: number;
    outcome?: string;
    onUpdatedCount?: number;
    statuses?: string[];
    reason?: string;
    httpStatus?: number;
    httpError?: string;
    url?: string;
  }>;
  /** Max entries to retain in preloadHistory (default 5). */
  preloadHistoryMax?: number;

  constructor(init?: Partial<TabConfig>) {
    Object.assign(this, init);
  }
}
